FROM alpine
MAINTAINER alex@varslashblog

ENV testfile=testJson.json
VOLUME testVolume
WORKDIR /testVolume
ADD https://raw.githubusercontent.com/injNinja/scripts/master/testDockerfile/testJson.json .
RUN apk add --update --no-cache curl jq
CMD ls -latr . && jq -C '.' $testfile
